// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { AppErrorResponse, PendingUpdate } from "../bindings";

/** Commands */
export const commands = {
	/**  A release newer than the running build, or `None` when this build is the latest. */
	checkUpdate: () => __TAURI_INVOKE<({ ok: true; value: PendingUpdate | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:app-update|check_update"),
	/**  Download the offered release's installer ahead of the install. */
	downloadUpdate: () => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:app-update|download_update"),
	/**  Install the downloaded release and relaunch into it. */
	installUpdate: () => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:app-update|install_update"),
	/**  Drop the downloaded installer, so quitting installs nothing. */
	discardUpdate: () => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:app-update|discard_update"),
};

/* Constants */
export const commandNames = {"checkUpdate":"plugin:app-update|check_update","discardUpdate":"plugin:app-update|discard_update","downloadUpdate":"plugin:app-update|download_update","installUpdate":"plugin:app-update|install_update"} as const;
