// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { AppErrorResponse, AssetRef, BinDocumentId, MaterialProgram, PagePatch, ProgramRead, SheetImport, SheetSpec, SurfaceSource, UiCharacter, UiFont, UiFontCatalog, UiLoadout, UiShader, UiSpellTooltip, UiView } from "../bindings";

/** Commands */
export const commands = {
	/**
	 *  The view controller at `entry` in the open document `document`, with its base scene bin,
	 *  its manifest and every sprite resolved through the document's sandbox.
	 * 
	 *  `scene` is the open document of the base scene bin, which the view draws as it stands in
	 *  place of the file. `variant` is laid over that base as the client lays an override.
	 * 
	 *  # Errors
	 * 
	 *  Fails when `entry` is no object hash or the document has no object under it. A file or
	 *  sprite the view cannot reach is a warning on the answer.
	 */
	readUiView: (document: BinDocumentId, entry: string, scene: number | null, variant: {
	slot: string,
	document: BinDocumentId | null,
} | null) => __TAURI_INVOKE<({ ok: true; value: UiView }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|read_ui_view", { document, entry, scene, variant }),
	/**
	 *  The scene bin open as `document`, drawn as a view of its own for the element at `entry`: its
	 *  scenes and elements as they stand, with the manifest of the folder the file sits in.
	 * 
	 *  # Errors
	 * 
	 *  Fails when `entry` is no object hash, the document is closed or it has no object under it.
	 */
	readUiSceneView: (document: BinDocumentId, entry: string) => __TAURI_INVOKE<({ ok: true; value: UiView }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|read_ui_scene_view", { document, entry }),
	/**
	 *  The sample champion, summoner spells, runes and items a preview fills a controller's elements
	 *  with, read through the sandbox `document` opens in.
	 * 
	 *  An object the index has not reached, or a texture no archive holds, is absent from the answer.
	 * 
	 *  # Errors
	 * 
	 *  Fails when the document is closed.
	 */
	readUiLoadout: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: UiLoadout }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|read_ui_loadout", { document }),
	/**
	 *  Every character the object index holds a record for, with its name and icon, read through
	 *  the sandbox `document` opens in and the game's stringtable.
	 * 
	 *  An index that is not ready reads as no characters.
	 * 
	 *  # Errors
	 * 
	 *  Fails when the document is closed.
	 */
	readUiCharacters: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: UiCharacter[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|read_ui_characters", { document }),
	/**
	 *  The tooltips of the passive and abilities of the character `character`, such as `Ahri`, at
	 *  `level` and each spell at `rank`, read through the sandbox `document` opens in and the game's
	 *  stringtable. Level 0 reads as no character at all, per `read_character_tooltips`.
	 * 
	 *  A character the index has not reached reads as no tooltips.
	 * 
	 *  # Errors
	 * 
	 *  Fails when the document is closed.
	 */
	readUiTooltips: (document: BinDocumentId, character: string, level: number, rank: number) => __TAURI_INVOKE<({ ok: true; value: UiSpellTooltip[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|read_ui_tooltips", { document, character, level, rank }),
	/**
	 *  The `GameFontDescription` at `entry` in the open document `document`, its links followed
	 *  into the document and then into the `ux/fonts` its sandbox resolves.
	 * 
	 *  # Errors
	 * 
	 *  Fails when `entry` is no object hash or neither bin holds an object under it.
	 */
	readUiFont: (document: BinDocumentId, entry: string) => __TAURI_INVOKE<({ ok: true; value: UiFont }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|read_ui_font", { document, entry }),
	/**
	 *  The fonts and faces a text in the open document `document` can draw with: the document's
	 *  own, then those of the `ux/fonts` its sandbox resolves.
	 * 
	 *  # Errors
	 * 
	 *  Fails when the names or the project chunks the resolution reads are unavailable.
	 */
	readUiFontCatalog: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: UiFontCatalog }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|read_ui_font_catalog", { document }),
	/**
	 *  Import the PNG at `source` into the sheet `sheet` of the project `document` opens in, or put
	 *  it in place of the sprite `replace`, per section 5 of docs/plans/atlas-ui-editor.md.
	 * 
	 *  A new sheet's page lands in the layer the document declares into, and in the archive folder
	 *  its own bin comes from.
	 * 
	 *  # Errors
	 * 
	 *  Fails when the document is closed or opens in no project, when the image cannot be read, and
	 *  when the sheet would outgrow one page.
	 */
	atlasImportSprite: (document: BinDocumentId, sheet: string, source: string, replace: string | null) => __TAURI_INVOKE<({ ok: true; value: SheetImport }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|atlas_import_sprite", { document, sheet, source, replace }),
	/**
	 *  Copy the `.ttf` or `.otf` at `source` into the layer and archive the document `document`
	 *  writes to, answering the path a `FontType` names it by.
	 * 
	 *  # Errors
	 * 
	 *  Fails when the document opens in no project or writes to no layer, for a file of another
	 *  type, and when the copy cannot be written.
	 */
	atlasImportFontFile: (document: BinDocumentId, source: string) => __TAURI_INVOKE<({ ok: true; value: string }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|atlas_import_font_file", { document, source }),
	/**
	 *  Make a surface named `name` on the sheet `sheet` of the project `document` opens in, per
	 *  section 5 of docs/plans/atlas-ui-editor.md: the image of `source`, its slice lines found in it,
	 *  so it stretches to any element's size.
	 * 
	 *  # Errors
	 * 
	 *  Fails when the document is closed or opens in no project, when the image cannot be read, and
	 *  when the sheet would outgrow one page.
	 */
	atlasMakeSurface: (document: BinDocumentId, sheet: string, name: string, source: SurfaceSource) => __TAURI_INVOKE<({ ok: true; value: SheetImport }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|atlas_make_surface", { document, sheet, name, source }),
	/**
	 *  Paste the PNG at `source` over the sprite at `uv` of the game texture `page`, and rebuild the
	 *  page into the layer the document `document` writes to, per section 5 of
	 *  docs/plans/atlas-ui-editor.md. Every element naming a sprite of the page keeps its rect.
	 * 
	 *  Answers none, writing nothing, where the game holds no `.tex` at `page` or the image is not the
	 *  sprite's size, which an import onto the project's sheet takes instead.
	 * 
	 *  # Errors
	 * 
	 *  Fails when the document is closed or opens in no project, and when the page or the image
	 *  cannot be read or the page cannot be written.
	 */
	atlasPatchSprite: (document: BinDocumentId, page: string, uv: [(number | null), (number | null), (number | null), (number | null)], source: string) => __TAURI_INVOKE<({ ok: true; value: PagePatch | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|atlas_patch_sprite", { document, page, uv, source }),
	/**
	 *  The spec of the sheet `sheet` of the project `document` opens in, none where it has not made
	 *  that sheet.
	 * 
	 *  # Errors
	 * 
	 *  Fails when the document is closed or opens in no project, and when the spec cannot be read.
	 */
	atlasSheet: (document: BinDocumentId, sheet: string) => __TAURI_INVOKE<({ ok: true; value: SheetSpec | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|atlas_sheet", { document, sheet }),
	/**
	 *  Write the sprite at `uv` on the page `texture` to `destination` as a PNG, at the page's own
	 *  resolution, for an image editor to open and the import to take back.
	 * 
	 *  # Errors
	 * 
	 *  Fails when the page cannot be read or decoded, when `uv` covers none of it, and when
	 *  `destination` cannot be written.
	 */
	atlasExportSprite: (texture: AssetRef, uv: [(number | null), (number | null), (number | null), (number | null)], destination: string) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|atlas_export_sprite", { texture, uv, destination }),
	/**
	 *  The programs of the icon materials `entries`, one for one and in that order, and none where
	 *  nothing declares one.
	 * 
	 *  A material is read out of the first of the open `documents` that declares it, which is how a
	 *  project's own material draws before its save, and otherwise out of the game chunk the object
	 *  index names for it. Names and assets resolve as the first document's do.
	 * 
	 *  # Errors
	 * 
	 *  Fails when the names or the project chunks the resolution reads are unavailable.
	 */
	readUiMaterialPrograms: (documents: BinDocumentId[], entries: string[]) => __TAURI_INVOKE<({ ok: true; value: (MaterialProgram | null)[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|read_ui_material_programs", { documents, entries }),
	/**
	 *  The programs of `shaders`, one for one and in that order, translated.
	 * 
	 *  The shaders are the ones `document` resolves against, and the install's alone where it
	 *  is none. Translations are cached as `read_material_programs` caches them.
	 * 
	 *  # Errors
	 * 
	 *  Fails when the names or the project chunks the resolution reads are unavailable.
	 */
	readUiPrograms: (document: number | null, shaders: UiShader[]) => __TAURI_INVOKE<({ ok: true; value: ProgramRead[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:atlas|read_ui_programs", { document, shaders }),
};

/* Constants */
export const commandNames = {"atlasExportSprite":"plugin:atlas|atlas_export_sprite","atlasImportFontFile":"plugin:atlas|atlas_import_font_file","atlasImportSprite":"plugin:atlas|atlas_import_sprite","atlasMakeSurface":"plugin:atlas|atlas_make_surface","atlasPatchSprite":"plugin:atlas|atlas_patch_sprite","atlasSheet":"plugin:atlas|atlas_sheet","readUiCharacters":"plugin:atlas|read_ui_characters","readUiFont":"plugin:atlas|read_ui_font","readUiFontCatalog":"plugin:atlas|read_ui_font_catalog","readUiLoadout":"plugin:atlas|read_ui_loadout","readUiMaterialPrograms":"plugin:atlas|read_ui_material_programs","readUiPrograms":"plugin:atlas|read_ui_programs","readUiSceneView":"plugin:atlas|read_ui_scene_view","readUiTooltips":"plugin:atlas|read_ui_tooltips","readUiView":"plugin:atlas|read_ui_view"} as const;
