// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { AppErrorResponse, AppInfo, PlatformSupport, StorageMedium } from "../bindings";

/** Commands */
export const commands = {
	/**  Get basic app information. */
	getAppInfo: () => __TAURI_INVOKE<({ ok: true; value: AppInfo }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:desktop|get_app_info"),
	/**  Get platform-specific feature flags. */
	getPlatformSupport: () => __TAURI_INVOKE<({ ok: true; value: PlatformSupport }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:desktop|get_platform_support"),
	/**
	 *  Reveal the main window once the frontend has finished its initial render.
	 * 
	 *  The window is created hidden (`visible: false` in `tauri.conf.json`) to avoid a
	 *  white flash while the WebView loads. The frontend calls this after it mounts.
	 *  When the user has opted to start in the tray, the window stays hidden — the tray
	 *  icon (or an available update, handled in the UI) reveals it later.
	 */
	showMainWindow: () => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:desktop|show_main_window"),
	/**  Opens a file location in the system file explorer. */
	revealInExplorer: (path: string) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:desktop|reveal_in_explorer", { path }),
	/**
	 *  Minimizes the window to the system tray if the setting is enabled,
	 *  otherwise performs a regular minimize.
	 */
	minimizeToTray: () => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:desktop|minimize_to_tray"),
	/**
	 *  Detect whether the given path is on an SSD, HDD, or unknown medium.
	 * 
	 *  Returns `Unknown` on non-Windows platforms and for any path we can't
	 *  resolve to a local volume (e.g. UNC paths, missing drives, permission
	 *  errors). Callers should treat `Unknown` as "don't warn" rather than
	 *  blocking the UI.
	 */
	detectStorageMedium: (path: string) => __TAURI_INVOKE<({ ok: true; value: StorageMedium }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:desktop|detect_storage_medium", { path }),
};

/* Constants */
export const commandNames = {"detectStorageMedium":"plugin:desktop|detect_storage_medium","getAppInfo":"plugin:desktop|get_app_info","getPlatformSupport":"plugin:desktop|get_platform_support","minimizeToTray":"plugin:desktop|minimize_to_tray","revealInExplorer":"plugin:desktop|reveal_in_explorer","showMainWindow":"plugin:desktop|show_main_window"} as const;
