// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { AppErrorResponse, DecodedIncident, DiagnosticReport_Serialize, Incident_Serialize, UiError } from "../bindings";

/** Commands */
export const commands = {
	runDiagnostics: () => __TAURI_INVOKE<({ ok: true; value: DiagnosticReport_Serialize }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:diagnostics|run_diagnostics"),
	/**
	 *  Launch an elevated PowerShell window so the user can run a fix command.
	 * 
	 *  On click of a "Run as administrator" button in the diagnostics UI, the
	 *  frontend copies the command to the clipboard and then calls this command.
	 *  We `ShellExecuteW` PowerShell with the `runas` verb (UAC prompt), then
	 *  `-NoExit` so the window stays open. When `with_banner` is true a short
	 *  hint line is printed up front telling the user the command is on their
	 *  clipboard and they should paste (Ctrl+V or right-click) and press Enter.
	 * 
	 *  Why not auto-execute the command? Auto-running registry deletes from a
	 *  freshly-elevated PowerShell with no review step is a footgun — the user
	 *  should at least see the command they're about to execute. Paste-then-Enter
	 *  is one extra keystroke and gives them a chance to bail out.
	 */
	openElevatedTerminal: (withBanner: boolean) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:diagnostics|open_elevated_terminal", { withBanner }),
	/**  Every incident the store holds, newest first. */
	listIncidents: () => __TAURI_INVOKE<({ ok: true; value: Incident_Serialize[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:diagnostics|list_incidents"),
	/**  Marks an incident dismissed. The verdict line goes, and the row dims. */
	dismissIncident: (id: string) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:diagnostics|dismiss_incident", { id }),
	/**  Marks every undismissed incident dismissed, and answers the ids it touched. */
	dismissAllIncidents: () => __TAURI_INVOKE<({ ok: true; value: string[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:diagnostics|dismiss_all_incidents"),
	/**  Reveals the incident's game log in the file manager. */
	revealGameLog: (id: string) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:diagnostics|reveal_game_log", { id }),
	/**
	 *  The incident as the text a support thread wants, with its token on the
	 *  second line. `hints` are the verdict's hints as the catalog renders them.
	 */
	incidentReport: (id: string, hints: string[]) => __TAURI_INVOKE<({ ok: true; value: string }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:diagnostics|incident_report", { id, hints }),
	/**  The incident folded into one short string, for a URL or a chat. */
	incidentToken: (id: string) => __TAURI_INVOKE<({ ok: true; value: string }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:diagnostics|incident_token", { id }),
	/**
	 *  Reads a token back, from the token alone or from a pasted report or URL
	 *  that carries one, against this build's tables.
	 */
	decodeIncidentToken: (token: string) => __TAURI_INVOKE<({ ok: true; value: DecodedIncident }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:diagnostics|decode_incident_token", { token }),
	/**
	 *  The pseudonym today's diagnostics would travel under, if any would.
	 * 
	 *  Answers `None` when nothing is collected, so the Privacy card can say that
	 *  rather than show an identity that reaches no one.
	 */
	telemetryIdentity: () => __TAURI_INVOKE<({ ok: true; value: string | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:diagnostics|telemetry_identity"),
	/**
	 *  Mint a new diagnostics secret, breaking the link to everything sent before.
	 * 
	 *  Takes effect at once rather than at the next midnight, because a reader who
	 *  presses it is asking for the link to break now. Answers the new pseudonym.
	 */
	resetTelemetrySecret: () => __TAURI_INVOKE<({ ok: true; value: string | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:diagnostics|reset_telemetry_secret"),
	/**
	 *  Report a crash the frontend caught, which is its only route to the wire.
	 * 
	 *  The frontend does not reach the network, so a boundary, a window error and a
	 *  rejection all come here and are queued on the one egress path.
	 */
	trackUiError: (error: UiError) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:diagnostics|track_ui_error", { error }),
};

/* Constants */
export const commandNames = {"decodeIncidentToken":"plugin:diagnostics|decode_incident_token","dismissAllIncidents":"plugin:diagnostics|dismiss_all_incidents","dismissIncident":"plugin:diagnostics|dismiss_incident","incidentReport":"plugin:diagnostics|incident_report","incidentToken":"plugin:diagnostics|incident_token","listIncidents":"plugin:diagnostics|list_incidents","openElevatedTerminal":"plugin:diagnostics|open_elevated_terminal","resetTelemetrySecret":"plugin:diagnostics|reset_telemetry_secret","revealGameLog":"plugin:diagnostics|reveal_game_log","runDiagnostics":"plugin:diagnostics|run_diagnostics","telemetryIdentity":"plugin:diagnostics|telemetry_identity","trackUiError":"plugin:diagnostics|track_ui_error"} as const;
