// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { AppErrorResponse, Champion, ExtractOptions, ExtractPlan, ExtractSummary, ExtractTarget, GameDirListing, GameFileEntry, GameFindResult, GameIndexStats, GameSearchResult, GameWadEntry, GameWadSummary, HashtableCacheStatus, HashtableSyncReport, HashtableUpdateCheck_Serialize, SearchFor, StringKeySearchResult, WadSource, WorkshopFileKind } from "../bindings";

/** Commands */
export const commands = {
	/**  Report what the folded index of `source` holds, building it on first use. */
	getGameIndex: (source: WadSource) => __TAURI_INVOKE<({ ok: true; value: GameIndexStats }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|get_game_index", { source }),
	/**
	 *  List one directory of the folded index of `source`.
	 * 
	 *  `path` is `""` for the root, and otherwise a path a previous listing
	 *  returned. Path hashes resolve through the shared hashtable cache when it is
	 *  populated. Otherwise every file reads as its hash.
	 */
	readGameDir: (path: string, source: WadSource) => __TAURI_INVOKE<({ ok: true; value: GameDirListing }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|read_game_dir", { path, source }),
	/**
	 *  Drop the built index of `source`, so the next read walks the install again.
	 * 
	 *  Unmounts the cached archives with it, and for the game drops the object
	 *  index, which was fed by this one. Asking for a fresh index is the one signal
	 *  the app gets that the install changed under it, and a mount taken before a
	 *  patch would keep answering from the chunk table it read then.
	 */
	refreshGameIndex: (source: WadSource) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|refresh_game_index", { source }),
	/**
	 *  Rank every file of the install against `query`, best first.
	 * 
	 *  The scan reads the index rather than a list of paths, because building
	 *  819,136 of those per keystroke costs more than the matching does. A call
	 *  that a later one overtakes gives up part way and says so, so a query typed
	 *  one character at a time runs one whole scan rather than one per character.
	 * 
	 *  An empty query matches nothing. The palette only reaches this source once
	 *  something is typed.
	 */
	searchGameIndex: (query: string, search: SearchFor) => __TAURI_INVOKE<({ ok: true; value: GameSearchResult }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|search_game_index", { query, search }),
	/**
	 *  Every file of `source` matching `pattern`, in tree order.
	 * 
	 *  The full-results twin of [`search_game_index`]: nothing is ranked, every
	 *  hit comes back up to the index's own cap, and `regex` reads the pattern as
	 *  a regular expression rather than as its characters. Either way the match is
	 *  case-insensitive, which is the only case a resolved WAD path has.
	 * 
	 *  An empty pattern matches nothing rather than everything. A pattern that
	 *  does not parse reports `VALIDATION_FAILED` with the parser's own message,
	 *  which the search box shows under the input.
	 */
	findInGameIndex: (pattern: string, regex: boolean, source: WadSource) => __TAURI_INVOKE<({ ok: true; value: GameFindResult }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|find_in_game_index", { pattern, regex, source }),
	/**
	 *  The install's copy of each of `paths`, by path. A path the install does not ship is
	 *  absent.
	 * 
	 *  For the `file` links of a page of bin rows, checked in one call. Lowercased and then
	 *  looked for by hash, which is what `DocumentAssets::locate` does: a chunk no table
	 *  names is reached by its path's hash, and the two lookups must not disagree about
	 *  whether the install holds a file.
	 */
	locateGameFiles: (paths: string[]) => __TAURI_INVOKE<({ ok: true; value: { [key in string]: GameFileEntry } }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|locate_game_files", { paths }),
	/**  List the WAD archives of `source`, sorted by name. */
	getGameWads: (source: WadSource) => __TAURI_INVOKE<({ ok: true; value: GameWadSummary[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|get_game_wads", { source }),
	/**
	 *  Read the chunk list of one WAD archive of `source`.
	 * 
	 *  Path hashes resolve through the shared hashtable cache when it is
	 *  populated. Otherwise every path comes back null.
	 */
	readGameWad: (wadName: string, source: WadSource) => __TAURI_INVOKE<({ ok: true; value: GameWadEntry[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|read_game_wad", { wadName, source }),
	/**
	 *  What extracting `targets` would write, before anything is written.
	 * 
	 *  The dialog's summary line reads this, so a user sees the count, the size and
	 *  the archives before choosing a destination. `kinds` are the browser's filter
	 *  chips, and `null` means every kind.
	 */
	planGameExtract: (targets: ExtractTarget[], kinds: WorkshopFileKind[] | null, source: WadSource) => __TAURI_INVOKE<({ ok: true; value: ExtractPlan }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|plan_game_extract", { targets, kinds, source }),
	/**
	 *  Write every chunk the targets name into `options.destination`.
	 * 
	 *  Progress arrives as `extract-progress`, throttled rather than one event per
	 *  chunk. Answers `None` when an extract is already running, which is what a
	 *  double-clicked Extract button looks like.
	 */
	extractGameFiles: (targets: ExtractTarget[], options: ExtractOptions, source: WadSource) => __TAURI_INVOKE<({ ok: true; value: ExtractSummary | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|extract_game_files", { targets, options, source }),
	/**
	 *  Call off the extract that is in flight, if there is one.
	 * 
	 *  Answers `false` when nothing was running, which is what a Cancel pressed
	 *  just as the run finished looks like. The files written so far stay, because
	 *  each one was written whole.
	 */
	cancelExtract: () => __TAURI_INVOKE<({ ok: true; value: boolean }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|cancel_extract"),
	/**
	 *  Report what the shared hashtable cache currently holds.
	 * 
	 *  A cache that was never synced is a normal report, not an error.
	 */
	getHashtableCacheStatus: () => __TAURI_INVOKE<({ ok: true; value: HashtableCacheStatus }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|get_hashtable_cache_status"),
	/**
	 *  Report what the latest published release has that the cache does not.
	 * 
	 *  Reads the remote manifest and nothing else: no download, no install, and no
	 *  update lock, so this is safe to run unasked and safe while another process
	 *  is midway through a sync. The meta schema database is asked the same
	 *  question, and answers for itself.
	 */
	checkHashtableUpdates: () => __TAURI_INVOKE<({ ok: true; value: HashtableUpdateCheck_Serialize }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|check_hashtable_updates"),
	/**
	 *  Download the latest published hashtables into the shared cache.
	 * 
	 *  Emits `hashtable-sync-progress` once per asset download. `force`
	 *  re-downloads every table even when the local copy already matches.
	 * 
	 *  A run that installed something drops everything read out of the old tables,
	 *  so the next caller sees the names the new ones give.
	 */
	syncHashtables: (force: boolean) => __TAURI_INVOKE<({ ok: true; value: HashtableSyncReport }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|sync_hashtables", { force }),
	/**
	 *  Search known stringtable field names for the workshop strings editor.
	 * 
	 *  The first call builds the suggestion index, reading the shared cache's
	 *  `rst-xxh3` table and the game stringtable for value previews, so it can take
	 *  a moment. Subsequent calls are instant.
	 */
	searchStringKeys: (query: string, limit: number | null) => __TAURI_INVOKE<({ ok: true; value: StringKeySearchResult }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|search_string_keys", { query, limit }),
	/**
	 *  Current in-game text for string-table keys, for the override editor and the bin editor.
	 * 
	 *  Shares the suggestion index with [`search_string_keys`], first-call build
	 *  cost included, on a blocking thread because a bin opening asks for it. A key
	 *  the game does not resolve is absent from the map.
	 */
	lookupStringValues: (keys: string[]) => __TAURI_INVOKE<({ ok: true; value: { [key in string]: string } }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|lookup_string_values", { keys }),
	/**
	 *  Every champion the install ships, with its name and icon, in natural order.
	 * 
	 *  Read out of each champion's own archive, so neither index is built. An archive the string
	 *  table names no character for, such as `TFTChampion`, is left out, unless the table names
	 *  none at all because it could not be read.
	 * 
	 *  # Errors
	 * 
	 *  Fails when no League install is configured, or its champions directory cannot be listed.
	 */
	readChampions: () => __TAURI_INVOKE<({ ok: true; value: Champion[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:game|read_champions"),
};

/* Constants */
export const commandNames = {"cancelExtract":"plugin:game|cancel_extract","checkHashtableUpdates":"plugin:game|check_hashtable_updates","extractGameFiles":"plugin:game|extract_game_files","findInGameIndex":"plugin:game|find_in_game_index","getGameIndex":"plugin:game|get_game_index","getGameWads":"plugin:game|get_game_wads","getHashtableCacheStatus":"plugin:game|get_hashtable_cache_status","locateGameFiles":"plugin:game|locate_game_files","lookupStringValues":"plugin:game|lookup_string_values","planGameExtract":"plugin:game|plan_game_extract","readChampions":"plugin:game|read_champions","readGameDir":"plugin:game|read_game_dir","readGameWad":"plugin:game|read_game_wad","refreshGameIndex":"plugin:game|refresh_game_index","searchGameIndex":"plugin:game|search_game_index","searchStringKeys":"plugin:game|search_string_keys","syncHashtables":"plugin:game|sync_hashtables"} as const;
