// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { AppErrorResponse, HotkeyAction } from "../bindings";

/** Commands */
export const commands = {
	/**  Temporarily unregister all hotkeys (e.g. while capturing a new binding). */
	pauseHotkeys: () => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:hotkeys|pause_hotkeys"),
	/**  Re-register all hotkeys after capture mode ends. */
	resumeHotkeys: () => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:hotkeys|resume_hotkeys"),
	/**  Set (or clear) a global hotkey for the given action. */
	setHotkey: (action: HotkeyAction, accelerator: string | null) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:hotkeys|set_hotkey", { action, accelerator }),
};

/* Constants */
export const commandNames = {"pauseHotkeys":"plugin:hotkeys|pause_hotkeys","resumeHotkeys":"plugin:hotkeys|resume_hotkeys","setHotkey":"plugin:hotkeys|set_hotkey"} as const;
