// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { AppErrorResponse, FileTypeStatus, IntegrationAction, IntegrationRelease, IntegrationStatus, MenuConflictPolicy, Tool } from "../bindings";

/** Commands */
export const commands = {
	/**  Local executable and Explorer state for each tool. */
	integrationStatus: () => __TAURI_INVOKE<({ ok: true; value: IntegrationStatus[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:integrations|integration_status"),
	/**  Latest stable release available for a tool. */
	integrationRelease: (tool: Tool) => __TAURI_INVOKE<({ ok: true; value: IntegrationRelease }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:integrations|integration_release", { tool }),
	/**  Apply an explicit installation or context-menu change. */
	changeIntegration: (tool: Tool, action: IntegrationAction, conflicts: MenuConflictPolicy) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:integrations|change_integration", { tool, action, conflicts }),
	/**  Cancel a matching download before registration begins. */
	cancelIntegrationDownload: (operationId: string) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:integrations|cancel_integration_download", { operationId }),
	/**  Which program Explorer opens each mod file type with. */
	fileTypeStatus: () => __TAURI_INVOKE<({ ok: true; value: FileTypeStatus[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:integrations|file_type_status"),
	/**  Open the app's page in Windows' Default apps settings. */
	openDefaultApps: () => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:integrations|open_default_apps"),
};

/* Constants */
export const commandNames = {"cancelIntegrationDownload":"plugin:integrations|cancel_integration_download","changeIntegration":"plugin:integrations|change_integration","fileTypeStatus":"plugin:integrations|file_type_status","integrationRelease":"plugin:integrations|integration_release","integrationStatus":"plugin:integrations|integration_status","openDefaultApps":"plugin:integrations|open_default_apps"} as const;
