// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { AppErrorResponse, InstallMismatch, LaunchAvailability, LaunchOutcome, SessionStarted } from "../bindings";

/** Commands */
export const commands = {
	/**  Ask the Riot Client to launch League. */
	launchLeague: (target: {
	productId: string,
	patchlineId: string,
} | null) => __TAURI_INVOKE<({ ok: true; value: LaunchOutcome | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:launcher|launch_league", { target }),
	/**
	 *  Call off the launch that is in flight, if there is one.
	 * 
	 *  Answers `false` when nothing was running, which is what a Cancel pressed
	 *  just as the request landed looks like.
	 * 
	 *  Stopping abandons the wait and not the launch: a request the Riot Client
	 *  already accepted still starts a game, exactly as a timeout would leave it.
	 */
	cancelLaunch: () => __TAURI_INVOKE<({ ok: true; value: boolean }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:launcher|cancel_launch"),
	/**
	 *  Ask the Riot Client to close the game it launched.
	 * 
	 *  Only useful while a session is live - the client refuses to close a product
	 *  it never started.
	 */
	stopLeague: () => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:launcher|stop_league"),
	/**
	 *  Whether a launch is possible right now. Drives the button's state, so it
	 *  reports rather than fails.
	 */
	getLaunchAvailability: () => __TAURI_INVOKE<({ ok: true; value: LaunchAvailability }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:launcher|get_launch_availability"),
	/**
	 *  The League session the Riot Client has open, and start following it.
	 * 
	 *  What a frontend asks on mount. Events alone are not enough there: a session
	 *  that began before the webview did announced itself to nobody, which is
	 *  exactly the case after the manager is restarted mid-game.
	 */
	getLeagueSession: () => __TAURI_INVOKE<({ ok: true; value: SessionStarted | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:launcher|get_league_session"),
	/**
	 *  The install the client's League session runs from, against the one the
	 *  manager is set up for.
	 * 
	 *  `None` when they agree, when no client or session answers, or when the
	 *  registry does not know the configured path. Read-only against the client.
	 */
	checkInstallMismatch: () => __TAURI_INVOKE<({ ok: true; value: InstallMismatch | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:launcher|check_install_mismatch"),
	/**
	 *  Points the manager at `install_root`, and puts the patcher session back up
	 *  on an overlay built from it.
	 * 
	 *  A running session is stopped, the path is saved the way Settings saves it,
	 *  and the session starts again with the config it ran with and a forced
	 *  rebuild. Without a running session the overlay is rebuilt and left for the
	 *  next start.
	 */
	switchLeagueInstall: (installRoot: string) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:launcher|switch_league_install", { installRoot }),
};

/* Constants */
export const commandNames = {"cancelLaunch":"plugin:launcher|cancel_launch","checkInstallMismatch":"plugin:launcher|check_install_mismatch","getLaunchAvailability":"plugin:launcher|get_launch_availability","getLeagueSession":"plugin:launcher|get_league_session","launchLeague":"plugin:launcher|launch_league","stopLeague":"plugin:launcher|stop_league","switchLeagueInstall":"plugin:launcher|switch_league_install"} as const;
