// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { Announcement, AppErrorResponse, Notice, ReleasePage } from "../bindings";

/** Commands */
export const commands = {
	/**  Read page `page` of the release feed, one-based as GitHub numbers it. */
	listReleases: (page: number) => __TAURI_INVOKE<({ ok: true; value: ReleasePage }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:news|list_releases", { page }),
	/**  Read the newest posts in the Announcements category. */
	listAnnouncements: () => __TAURI_INVOKE<({ ok: true; value: Announcement[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:news|list_announcements"),
	/**  Read the notices that concern this build right now. */
	listNotices: () => __TAURI_INVOKE<({ ok: true; value: Notice[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:news|list_notices"),
};

/* Constants */
export const commandNames = {"listAnnouncements":"plugin:news|list_announcements","listNotices":"plugin:news|list_notices","listReleases":"plugin:news|list_releases"} as const;
