// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { AppErrorResponse, ChecksumMismatchInfo, LinkedBinOffenderInfo, PatcherConfig, PatcherStatus } from "../bindings";

/** Commands */
export const commands = {
	/**
	 *  Start the patcher with the given configuration.
	 * 
	 *  Returns immediately after spawning a background thread that builds the overlay
	 *  and then runs the patcher loop. Progress is reported via events.
	 */
	startPatcher: (config: PatcherConfig) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:patcher|start_patcher", { config }),
	/**  Stop the running patcher. */
	stopPatcher: () => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:patcher|stop_patcher"),
	/**
	 *  Force a full rebuild of the active profile's overlay.
	 * 
	 *  Troubleshooting escape hatch: the incremental overlay builder can reuse a
	 *  previously-built (and possibly stale or incorrectly-built) WAD, so this
	 *  discards the cached overlay state and regenerates it from scratch. Refuses
	 *  while the patcher is running, since it rewrites the very files the running
	 *  session points at. Runs on a blocking thread and reports progress via the
	 *  same `overlay-progress` events as a normal patch.
	 */
	rebuildOverlay: () => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:patcher|rebuild_overlay"),
	/**  Get the current status of the patcher. */
	getPatcherStatus: () => __TAURI_INVOKE<({ ok: true; value: PatcherStatus }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:patcher|get_patcher_status"),
	/**
	 *  Linked-bin offenders found in the most recent overlay build, keyed by mod id.
	 * 
	 *  These are recorded as a byproduct of `start_patcher`'s single overlay build (and
	 *  any hot-reload), so this is a cheap read with no IO - it never builds the overlay
	 *  itself. Display names are resolved from the library index; mods absent from the
	 *  latest build (e.g. since-disabled) simply don't appear. Missing linked bins are
	 *  non-fatal at injection, so this is advisory: the frontend surfaces it as per-mod
	 *  badges and a reachable warning dialog.
	 */
	getLinkedBinOffenders: () => __TAURI_INVOKE<({ ok: true; value: { [key in string]: LinkedBinOffenderInfo } }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:patcher|get_linked_bin_offenders"),
	/**
	 *  Checksum mismatches found in the most recent overlay build, keyed by mod id.
	 * 
	 *  Recorded as a byproduct of the same build that records linked-bin offenders,
	 *  so this is a cheap read with no IO. A mismatch marks a badly-packed mod: its
	 *  container claimed a checksum its own bytes do not have. Never fatal - the
	 *  overlay carries the recomputed value, so this is advisory, surfaced per-mod
	 *  in mod details.
	 */
	getChecksumMismatches: () => __TAURI_INVOKE<({ ok: true; value: { [key in string]: ChecksumMismatchInfo[] } }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:patcher|get_checksum_mismatches"),
};

/* Constants */
export const commandNames = {"getChecksumMismatches":"plugin:patcher|get_checksum_mismatches","getLinkedBinOffenders":"plugin:patcher|get_linked_bin_offenders","getPatcherStatus":"plugin:patcher|get_patcher_status","rebuildOverlay":"plugin:patcher|rebuild_overlay","startPatcher":"plugin:patcher|start_patcher","stopPatcher":"plugin:patcher|stop_patcher"} as const;
