// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { AppErrorResponse, ForcibleMapSkin, MapDecoration, Settings_Deserialize, Settings_Serialize } from "../bindings";

/** Commands */
export const commands = {
	/**  Get current settings. */
	getSettings: () => __TAURI_INVOKE<({ ok: true; value: Settings_Serialize }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:settings|get_settings"),
	/**  Save settings. */
	saveSettings: (settings: Settings_Deserialize) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:settings|save_settings", { settings }),
	/**
	 *  The settings a fresh install starts with.
	 * 
	 *  Read once by the settings UI, so a row can say whether it is still at its
	 *  default and what resetting it would put back. The `get_` prefix is against
	 *  C-GETTER and stays, because `get_settings` is its neighbour.
	 */
	getDefaultSettings: () => __TAURI_INVOKE<({ ok: true; value: Settings_Serialize }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:settings|get_default_settings"),
	/**  Auto-detect League of Legends installation path. */
	autoDetectLeaguePath: () => __TAURI_INVOKE<({ ok: true; value: string | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:settings|auto_detect_league_path"),
	/**  Validate a League installation path. */
	validateLeaguePath: (path: string) => __TAURI_INVOKE<({ ok: true; value: boolean }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:settings|validate_league_path", { path }),
	/**  Check if initial setup is required (league path not configured). */
	checkSetupRequired: () => __TAURI_INVOKE<({ ok: true; value: boolean }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:settings|check_setup_required"),
	/**
	 *  Whether League is configured to launch as administrator (an AppCompatFlags
	 *  `RUNASADMIN` layer on its executable).
	 * 
	 *  When true, the patcher auto-elevates the injection host even if the
	 *  "run injector elevated" setting is off, since an elevated game can only be
	 *  injected by an elevated host. The settings UI surfaces this so users
	 *  understand why a UAC prompt may appear despite the setting being off.
	 */
	detectLeagueRunAsAdmin: () => __TAURI_INVOKE<({ ok: true; value: boolean }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:settings|detect_league_run_as_admin"),
	/**
	 *  List every WAD filename under the configured League install's `DATA` directory.
	 * 
	 *  Used by the WAD blocklist editor for autocomplete and regex match previews.
	 *  Returns lowercased filenames sorted alphabetically.
	 */
	listAvailableWads: () => __TAURI_INVOKE<({ ok: true; value: string[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:settings|list_available_wads"),
	/**  Every map skin the configured install can show in place of the one a server names. */
	listForcibleMapSkins: () => __TAURI_INVOKE<({ ok: true; value: ForcibleMapSkin[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:settings|list_forcible_map_skins"),
	/**  Every map decoration a mutator switches in the configured install. */
	listMapDecorations: () => __TAURI_INVOKE<({ ok: true; value: MapDecoration[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:settings|list_map_decorations"),
};

/* Constants */
export const commandNames = {"autoDetectLeaguePath":"plugin:settings|auto_detect_league_path","checkSetupRequired":"plugin:settings|check_setup_required","detectLeagueRunAsAdmin":"plugin:settings|detect_league_run_as_admin","getDefaultSettings":"plugin:settings|get_default_settings","getSettings":"plugin:settings|get_settings","listAvailableWads":"plugin:settings|list_available_wads","listForcibleMapSkins":"plugin:settings|list_forcible_map_skins","listMapDecorations":"plugin:settings|list_map_decorations","saveSettings":"plugin:settings|save_settings","validateLeaguePath":"plugin:settings|validate_league_path"} as const;
