// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { AppErrorResponse, AssetRef, BinChange, BinDocumentHandle, BinDocumentId, BinEdit, BinFindResult, BinRow, BinRows, ChangeBaseline, ChoiceQuery, Choices, ClassDocs, ClassSchema, DeclaredModuleChoice, DeclaredState, Declaring, Dependency, EditOutcome, HexBinHash, HistoryStep, LayerOverride, ModuleAction, ReadOnly, Reshape, RowDeclaration, SandboxRef } from "../bindings";

/** Commands */
export const commands = {
	/**
	 *  Hold `asset` open as a bin in `sandbox`, answering the header and the rows at depth zero.
	 * 
	 *  A game chunk a layer of the sandbox ships opens as that layer's file, and one no layer
	 *  ships opens as a declared document of the project (ADR-0042, ADR-0056). With no `entry`,
	 *  the rows are one per object. With one, `0x` and eight hex digits, the rows are that
	 *  object's properties and the answer carries its header facts.
	 */
	binOpen: (sandbox: SandboxRef, asset: AssetRef, entry: string | null) => __TAURI_INVOKE<({ ok: true; value: BinDocumentHandle }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_open", { sandbox, asset, entry }),
	/**
	 *  Hold the UI variant `asset` open in `sandbox` laid over its base scene bin `base`,
	 *  answering the header and one row per object.
	 * 
	 *  In a project, a variant no layer ships opens as a declared variant: the base and the variant
	 *  with the project's declarations of each, and an edit landing in a `target` module of `path`,
	 *  the variant chunk's path (league-mod ADR-0035). Any other variant opens as its file.
	 */
	binOpenVariant: (sandbox: SandboxRef, asset: AssetRef, base: AssetRef, path: string) => __TAURI_INVOKE<({ ok: true; value: BinDocumentHandle }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_open_variant", { sandbox, asset, base, path }),
	/**
	 *  Write an open document's edits to its layer file, as a delta over the bytes it opened.
	 * 
	 *  A document no patch touched writes nothing. ADR-0040.
	 */
	binSave: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_save", { document }),
	/**
	 *  Read an open document's file again, dropping the edits its tree held.
	 * 
	 *  Every id over the asset reads the file as it is on disk.
	 */
	binReload: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_reload", { document }),
	/**  Drop one id. Its asset leaves the store with its last id. */
	binClose: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_close", { document }),
	/**  The rows at depth zero of an open file, one per object, read again after an edit. */
	binRoots: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: BinRow[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_roots", { document }),
	/**
	 *  The rows under one node of an open document, `offset` in and at most `limit` of them.
	 * 
	 *  `entry` is the object's hash as `0x` and eight hex digits. `path` is the wire form
	 *  of the property path, empty for the object itself. Every row carries what the meta
	 *  schema declares for its field at the install's build.
	 */
	binChildren: (document: BinDocumentId, entry: string, path: string, offset: number, limit: number) => __TAURI_INVOKE<({ ok: true; value: BinRows }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_children", { document, entry, path, offset, limit }),
	/**
	 *  The rows under each of several nodes of an open document, in the order asked.
	 * 
	 *  The projected read of "The projected read" in docs/ux/BIN_EDITOR.md, which a class
	 *  layout and a value row use in place of one [`bin_children`] call per node. Each path
	 *  answers one page, a path reaching nothing answers an empty one, and a call past the
	 *  row cap is refused so the caller batches.
	 */
	binRead: (document: BinDocumentId, entry: string, paths: string[]) => __TAURI_INVOKE<({ ok: true; value: BinRows[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_read", { document, entry, paths }),
	/**
	 *  Every row of an open document whose name or value holds `query`, in tree order.
	 * 
	 *  `entry`, `0x` and eight hex digits, narrows the search to one object, which is what
	 *  an object tab draws. The project bar's `@` scope asks this of the active tab.
	 */
	binFind: (document: BinDocumentId, entry: string | null, query: string) => __TAURI_INVOKE<({ ok: true; value: BinFindResult }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_find", { document, entry, query }),
	/**  The header's dependencies of an open document, as its rows draw them. */
	binDependencies: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: Dependency[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_dependencies", { document }),
	/**
	 *  What an add line of an open document offers, out of the meta schema at the install's
	 *  build. ADR-0051.
	 */
	binChoices: (document: BinDocumentId, query: ChoiceQuery) => __TAURI_INVOKE<({ ok: true; value: Choices }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_choices", { document, query }),
	/**  The value at `path` under the object `entry` of an open document, as clipboard text. */
	binCopyValue: (document: BinDocumentId, entry: string, path: string) => __TAURI_INVOKE<({ ok: true; value: string }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_copy_value", { document, entry, path }),
	/**
	 *  One class's fields and their declared kinds at the install's build.
	 * 
	 *  Read out of the meta schema. `None` for a class the schema does not describe.
	 *  `class_hash` is `0x` and eight hex digits.
	 */
	classSchema: (classHash: string) => __TAURI_INVOKE<({ ok: true; value: ClassSchema | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|class_schema", { classHash }),
	/**
	 *  Every class deriving from `class_hash` at the install's build, through any number of
	 *  bases. `class_hash` is `0x` and eight hex digits.
	 */
	derivedClasses: (classHash: string) => __TAURI_INVOKE<({ ok: true; value: HexBinHash[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|derived_classes", { classHash }),
	/**
	 *  The wiki's documentation for one class and every property declared on it or its bases.
	 * 
	 *  Reads the cache only, never the network. `None` where nothing is documented.
	 *  `class_hash` is `0x` and eight hex digits.
	 */
	classDocs: (classHash: string) => __TAURI_INVOKE<({ ok: true; value: ClassDocs | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|class_docs", { classHash }),
	/**
	 *  Refresh the cached documentation once per session, and return the session's revision.
	 * 
	 *  The revision increases when a newer copy is installed. When the publisher cannot be reached,
	 *  the cached copy and the revision stay unchanged.
	 */
	syncMetaDocs: () => __TAURI_INVOKE<({ ok: true; value: number }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|sync_meta_docs"),
	/**
	 *  Apply one edit to an open document, answering what the edit reports beside the change.
	 * 
	 *  Every id over the asset reads the edit, and nothing reaches the disk before [`bin_save`].
	 *  ADR-0051.
	 */
	binEdit: (document: BinDocumentId, edit: BinEdit) => __TAURI_INVOKE<({ ok: true; value: EditOutcome }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_edit", { document, edit }),
	/**
	 *  Move an open document's tree one `step` through its history, answering how its rows
	 *  moved, or null where that stack is empty.
	 * 
	 *  The file tab and the object tabs over one asset share the tree and its stacks.
	 */
	binHistory: (document: BinDocumentId, step: HistoryStep) => __TAURI_INVOKE<({ ok: true; value: Reshape | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_history", { document, step }),
	/**
	 *  Every property and object of an open document that differs from `baseline`: the file as
	 *  it was opened, or the installed game's copy of each object.
	 */
	binChanges: (document: BinDocumentId, baseline: ChangeBaseline) => __TAURI_INVOKE<({ ok: true; value: BinChange[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_changes", { document, baseline }),
	/**
	 *  Put the property at `path` under `entry` back to what `baseline` holds, as one undoable
	 *  edit. `entry` is `0x` and eight hex digits.
	 */
	binRevert: (document: BinDocumentId, entry: string, path: string, baseline: ChangeBaseline) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_revert", { document, entry, path, baseline }),
	/**
	 *  What the document says beside its rows: the layer it declares into, the project's
	 *  layers, and the rows a declaration of that layer touches. `None` for a document that
	 *  declares nothing. ADR-0042.
	 */
	binDeclared: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: DeclaredState | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_declared", { document }),
	/**
	 *  The rows of an open layer file that the declarations of its project override, or every
	 *  layer's declarations on a declared document. Empty for every other document. ADR-0056.
	 */
	binOverrides: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: LayerOverride[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_overrides", { document }),
	/**
	 *  Take edits on a declared document as declarations, or refuse them, answering the gate
	 *  it then stands behind. The project's "Use game data declarations". ADR-0042.
	 */
	binSetDeclaring: (document: BinDocumentId, declaring: Declaring) => __TAURI_INVOKE<({ ok: true; value: ReadOnly | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_set_declaring", { document, declaring }),
	/**
	 *  Write the edits that follow on a declared document to `module` of `layer`. ADR-0042,
	 *  ADR-0048.
	 */
	binDeclareInto: (document: BinDocumentId, layer: string, module: DeclaredModuleChoice) => __TAURI_INVOKE<({ ok: true; value: DeclaredState }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_declare_into", { document, layer, module }),
	/**
	 *  The row at `path` under `entry` as the declaration and the game-copy reference an author
	 *  would write for it, from any open bin. ADR-0042.
	 */
	binRowDeclaration: (document: BinDocumentId, entry: string, path: string) => __TAURI_INVOKE<({ ok: true; value: RowDeclaration }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|bin_row_declaration", { document, entry, path }),
	/**
	 *  Apply a module action to the manifest of `layer` of the project at `project_path`, with no
	 *  document to undo it. ADR-0048.
	 */
	declarationsModuleAction: (projectPath: string, layer: string, action: ModuleAction) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:bin|declarations_module_action", { projectPath, layer, action }),
};

/* Constants */
export const commandNames = {"binChanges":"plugin:bin|bin_changes","binChildren":"plugin:bin|bin_children","binChoices":"plugin:bin|bin_choices","binClose":"plugin:bin|bin_close","binCopyValue":"plugin:bin|bin_copy_value","binDeclareInto":"plugin:bin|bin_declare_into","binDeclared":"plugin:bin|bin_declared","binDependencies":"plugin:bin|bin_dependencies","binEdit":"plugin:bin|bin_edit","binFind":"plugin:bin|bin_find","binHistory":"plugin:bin|bin_history","binOpen":"plugin:bin|bin_open","binOpenVariant":"plugin:bin|bin_open_variant","binOverrides":"plugin:bin|bin_overrides","binRead":"plugin:bin|bin_read","binReload":"plugin:bin|bin_reload","binRevert":"plugin:bin|bin_revert","binRoots":"plugin:bin|bin_roots","binRowDeclaration":"plugin:bin|bin_row_declaration","binSave":"plugin:bin|bin_save","binSetDeclaring":"plugin:bin|bin_set_declaring","classDocs":"plugin:bin|class_docs","classSchema":"plugin:bin|class_schema","declarationsModuleAction":"plugin:bin|declarations_module_action","derivedClasses":"plugin:bin|derived_classes","syncMetaDocs":"plugin:bin|sync_meta_docs"} as const;
