// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { AppErrorResponse, CharacterSpells, ClassObjectCount, DeclaredObjects, HexBinHash, ObjectDir, ObjectFind, ObjectReferences, ObjectSearch, ReferenceQuery, SandboxRef } from "../bindings";

/** Commands */
export const commands = {
	/**
	 *  Build the object index, unless one is built or building.
	 * 
	 *  The game index is built first when it is not, because the object build is
	 *  fed by it. The call returns once the build lands, and a build that fails
	 *  leaves the failure in the state for a search to report.
	 */
	warmObjectIndex: () => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:objects|warm_object_index"),
	/**  Drop the object index, and the result of any build still running. */
	dropObjectIndex: () => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:objects|drop_object_index"),
	/**
	 *  Rank every bin object of the install against `query`, best first.
	 * 
	 *  Answers for the slot the index is in, so a query that arrives while the
	 *  build runs reads as building rather than as nothing. The scan carries a
	 *  generation of its own, apart from the game scan's, so a keystroke gives up
	 *  only the object scan it overtakes.
	 */
	searchObjectIndex: (query: string) => __TAURI_INVOKE<({ ok: true; value: ObjectSearch }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:objects|search_object_index", { query }),
	/**
	 *  Every object of the install matching `pattern`, in path order.
	 * 
	 *  The full-results twin of [`search_object_index`], the way [`find_in_game_index`]
	 *  is the game search's. `regex` reads the pattern as a regular expression, and
	 *  either way the match is case-insensitive. `class_term` is the `class:` term's value,
	 *  a name prefix or a hash, which narrows the objects to the classes it opens.
	 * 
	 *  An empty pattern with no class matches nothing. A pattern that does not parse
	 *  reports `VALIDATION_FAILED` with the parser's own message.
	 * 
	 *  [`find_in_game_index`]: crate::services::game::index::find_in_game_index
	 */
	findObjects: (pattern: string, regex: boolean, classTerm: string | null) => __TAURI_INVOKE<({ ok: true; value: ObjectFind }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:objects|find_objects", { pattern, regex, classTerm }),
	/**
	 *  What one prefix of the object tree holds.
	 * 
	 *  `prefix` is `""` for the root, `?` for the objects no table names, and otherwise a
	 *  path a listing gave. A prefix no object path runs through reports `INVALID_PATH`.
	 *  "Objects browser" in `docs/ux/PROJECT_EDITOR.md`.
	 */
	objectDir: (prefix: string) => __TAURI_INVOKE<({ ok: true; value: ObjectDir }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:objects|object_dir", { prefix }),
	/**  The install's spells below `Characters/{character}/Spells`. */
	characterSpells: (character: string) => __TAURI_INVOKE<({ ok: true; value: CharacterSpells }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:objects|character_spells", { character }),
	/**  How many objects of the install declare the class `class_hash`, for the class card. */
	classObjectCount: (classHash: HexBinHash) => __TAURI_INVOKE<({ ok: true; value: ClassObjectCount }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:objects|class_object_count", { classHash }),
	/**
	 *  Every declaration of each of `object_hashes` in `sandbox`, by hash.
	 * 
	 *  The install's declarations come from the index, in the slot it is in. The declarations
	 *  in the sandbox's layer files go before them (ADR-0056), and an install declaration in a
	 *  chunk a layer ships is removed, because the build packs the layer's copy instead. With
	 *  `document` open, the document's own declarations are added and every list is ordered as a
	 *  link resolves it (ADR-0028): this file, then a file the bin depends on, then the rest.
	 */
	declaredObjects: (sandbox: SandboxRef, objectHashes: string[], document: number | null) => __TAURI_INVOKE<({ ok: true; value: DeclaredObjects }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:objects|declared_objects", { sandbox, objectHashes, document }),
	/**
	 *  What `query` names, grouped by the file that holds it.
	 * 
	 *  A class answers from the index with every object the install declares as it. An
	 *  embedded class, an object and a file answer from a walk of `project`'s layers and
	 *  the install, reporting `reference-walk-progress` as it reads. The scan carries a
	 *  generation of its own, so a re-run gives up only the reference scan it overtakes.
	 * 
	 *  "The References document" in `docs/ux/PROJECT_EDITOR.md`.
	 */
	findReferences: (query: ReferenceQuery, project: string | null) => __TAURI_INVOKE<({ ok: true; value: ObjectReferences }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:objects|find_references", { query, project }),
	/**
	 *  Call off the walk in flight, if there is one.
	 * 
	 *  Answers `false` when nothing was walking, which is what a Cancel pressed as the
	 *  walk finished looks like. The walk answers with what it found.
	 */
	cancelReferenceWalk: () => __TAURI_INVOKE<({ ok: true; value: boolean }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:objects|cancel_reference_walk"),
};

/* Constants */
export const commandNames = {"cancelReferenceWalk":"plugin:objects|cancel_reference_walk","characterSpells":"plugin:objects|character_spells","classObjectCount":"plugin:objects|class_object_count","declaredObjects":"plugin:objects|declared_objects","dropObjectIndex":"plugin:objects|drop_object_index","findObjects":"plugin:objects|find_objects","findReferences":"plugin:objects|find_references","objectDir":"plugin:objects|object_dir","searchObjectIndex":"plugin:objects|search_object_index","warmObjectIndex":"plugin:objects|warm_object_index"} as const;
