// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { AnimationGraph, AppErrorResponse, AssetInfo, AssetRef, BinDocumentId, ClipHeader, EnginePass, MapCharacter, MapChunk, MapFiles, MapModel, MapParticle, MapPath, MapVariant, MaterialProgram, MaterialSource, MaterialTarget, PassProgram, ProgramOptions, SandboxRef, SkinModel, SpellPreview, VfxSystem, VfxTemplate } from "../bindings";

/** Commands */
export const commands = {
	/**
	 *  Report what a previewable asset holds, without decoding it.
	 * 
	 *  A file kind with no viewer comes back as [`AssetInfo::Unsupported`] rather
	 *  than an error, because a modder clicking through a tree meets one constantly
	 *  and the viewer draws it as a state.
	 */
	readAssetInfo: (asset: AssetRef) => __TAURI_INVOKE<({ ok: true; value: AssetInfo }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|read_asset_info", { asset }),
	/**
	 *  Write one previewed asset to a path the user picked.
	 * 
	 *  The extract of a single file, and not through the extractor: the user named
	 *  the file in a save dialog, so none of the naming rules apply and there is no
	 *  archive to walk. One chunk, read and written.
	 * 
	 *  The archive stays mounted afterwards, because the modder saving a copy of a
	 *  texture is looking through that archive.
	 */
	saveAssetCopy: (asset: AssetRef, destination: string) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|save_asset_copy", { asset, destination }),
	/**  Report whether the ritobin VS Code integration is installed. */
	detectRitobinIntegration: () => __TAURI_INVOKE<({ ok: true; value: boolean }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|detect_ritobin_integration"),
	/**
	 *  Open one asset as ritobin text in VS Code.
	 * 
	 *  `name` is what a hash table made of a game chunk's hash, which the reference
	 *  itself cannot carry. It names the copy the chunk is opened from.
	 */
	openAssetInRitobin: (asset: AssetRef, name: string | null) => __TAURI_INVOKE<({ ok: true; value: null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|open_asset_in_ritobin", { asset, name }),
	/**
	 *  The materials `targets` name, each with a translated program per pass.
	 * 
	 *  An entry is an object hash as `0x` and eight hex digits, or an object path, which is
	 *  hashed. The answer is one for one and in order, null where the bin declares no object
	 *  under the entry or the path reaches no struct. The shader defs are read beside the bin,
	 *  the project's copy first, and a read they refuse leaves every pass without a shader and
	 *  says so. Translations are kept under the app's data directory by the blob's hash.
	 * 
	 *  # Errors
	 * 
	 *  Fails when the source bin cannot be read or parsed.
	 */
	readMaterialPrograms: (source: MaterialSource, targets: MaterialTarget[], options: ProgramOptions) => __TAURI_INVOKE<({ ok: true; value: (MaterialProgram | null)[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|read_material_programs", { source, targets, options }),
	/**
	 *  The engine's own `pass`, translated. Translations are cached as
	 *  [`read_material_programs`] caches them.
	 * 
	 *  # Errors
	 * 
	 *  Fails when no document is open under a default skinned pass's `document`, and when the
	 *  names or the project chunks the resolution reads are unavailable.
	 */
	readEngineProgram: (pass: EnginePass, options: ProgramOptions) => __TAURI_INVOKE<({ ok: true; value: PassProgram }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|read_engine_program", { pass, options }),
	/**
	 *  The materials a map's submeshes name, and its lighting and screen effects.
	 * 
	 *  `map` is `MapContainer.mapPath`, an entry path such as
	 *  `Maps/MapGeometry/Map11/Base_SRX`, and `materials` are the entry paths the map's own
	 *  `LTKM` buffer carries, answered one for one and in that order. `document` names any
	 *  open document of the project whose layer answers first, and none resolves against the
	 *  install alone.
	 * 
	 *  A map nothing holds a `.materials.bin` for leaves every material unresolved rather
	 *  than failing the read, which draws the map flat. One whose file is there but will not
	 *  read is reported, because the caller keeps this answer for the app's life and a flat
	 *  map cached over a momentary failure is a map that never draws again.
	 */
	readMap: (document: number | null, map: MapPath, materials: string[]) => __TAURI_INVOKE<({ ok: true; value: MapModel }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|read_map", { document, map, materials }),
	/**
	 *  Every particle the open `.materials.bin` under `document` stands in its map.
	 * 
	 *  The systems they link are objects of the same document, so `read_vfx_system` answers
	 *  each against the handle this was asked with.
	 */
	readMapParticles: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: MapParticle[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|read_map_particles", { document }),
	/**
	 *  Every character the open `.materials.bin` under `document` stands in its map.
	 * 
	 *  Each names its skin by entry path, which lives in the character's own skin bin rather
	 *  than in this document.
	 */
	readMapCharacters: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: MapCharacter[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|read_map_characters", { document }),
	/**
	 *  The maps the `Map`, `MapSkin` or `MapContainer` at `entry` draws.
	 * 
	 *  Empty for a skin that links no container and for an object of any other class.
	 */
	readMapVariants: (document: BinDocumentId, entry: string) => __TAURI_INVOKE<({ ok: true; value: MapVariant[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|read_map_variants", { document, entry }),
	/**  Every chunk the open `.materials.bin` under `document` declares, and what each holds. */
	readMapOutline: (document: BinDocumentId) => __TAURI_INVOKE<({ ok: true; value: MapChunk[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|read_map_outline", { document }),
	/**
	 *  Where the two files of `map` live in `sandbox`, its layers checked before the install.
	 * 
	 *  So a mod that ships its own geometry draws it, and one that ships only materials draws
	 *  the install's geometry under them.
	 */
	locateMapFiles: (sandbox: SandboxRef, map: MapPath) => __TAURI_INVOKE<({ ok: true; value: MapFiles }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|locate_map_files", { sandbox, map }),
	/**
	 *  Where each of `paths` lives in `sandbox`, its layers checked before the install.
	 * 
	 *  One call for every file a scene is about to open. A path nothing holds is absent.
	 */
	locateFilesNear: (sandbox: SandboxRef, paths: string[]) => __TAURI_INVOKE<({ ok: true; value: { [key in string]: AssetRef } }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|locate_files_near", { sandbox, paths }),
	/**
	 *  One skin of an open document, as a viewport draws it.
	 * 
	 *  `entry` is the `SkinCharacterDataProperties` object's hash as `0x` and eight hex
	 *  digits. The shader defs are read beside the skin, the project's copy first, and a
	 *  read they refuse leaves every material on its own fields. A material or an effect
	 *  system the document does not declare is looked for through the files it links, as a
	 *  graph is.
	 */
	readSkin: (document: BinDocumentId, entry: string) => __TAURI_INVOKE<({ ok: true; value: SkinModel }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|read_skin", { document, entry }),
	/**
	 *  One animation graph: its clips with their files placed, and the maps they key into.
	 * 
	 *  `entry` is the `AnimationGraphData` object's hash as `0x` and eight hex digits. A
	 *  graph the open document does not declare is looked for through the files it links,
	 *  and a linked file that cannot be read is passed over.
	 */
	readAnimationGraph: (document: BinDocumentId, entry: string) => __TAURI_INVOKE<({ ok: true; value: AnimationGraph }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|read_animation_graph", { document, entry }),
	/**  The rate and the length of one `.anm`, which the clip table's rate column reads. */
	readClipHeader: (asset: AssetRef) => __TAURI_INVOKE<({ ok: true; value: ClipHeader }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|read_clip_header", { asset }),
	/**
	 *  Tangents saved into the viewed skin's project-layer mesh.
	 * 
	 *  # Errors
	 *  Fails when the skin or layer mesh is unavailable, baking fails, or the write fails.
	 */
	bakeSkinTangents: (document: BinDocumentId, entry: string) => __TAURI_INVOKE<({ ok: true; value: AssetRef }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|bake_skin_tangents", { document, entry }),
	/**  The missile inputs written on one spell in an open document. */
	readSpell: (document: BinDocumentId, entry: string) => __TAURI_INVOKE<({ ok: true; value: SpellPreview }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|read_spell", { document, entry }),
	/**
	 *  One particle system of an open document, with every reference resolved.
	 * 
	 *  `entry` is the object's hash as `0x` and eight hex digits. A class or field the hash
	 *  tables leave unnamed takes the meta schema's name. A custom material the document does
	 *  not declare is looked for through the files it links, and a linked file that cannot be
	 *  read is passed over.
	 */
	readVfxSystem: (document: BinDocumentId, entry: string) => __TAURI_INVOKE<({ ok: true; value: VfxSystem }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|read_vfx_system", { document, entry }),
	/**  Every VFX template of the catalog, which the Graph pane and the inspector offer. ADR-0058. */
	vfxTemplates: () => __TAURI_INVOKE<({ ok: true; value: VfxTemplate[] }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:preview|vfx_templates"),
};

/* Constants */
export const commandNames = {"bakeSkinTangents":"plugin:preview|bake_skin_tangents","detectRitobinIntegration":"plugin:preview|detect_ritobin_integration","locateFilesNear":"plugin:preview|locate_files_near","locateMapFiles":"plugin:preview|locate_map_files","openAssetInRitobin":"plugin:preview|open_asset_in_ritobin","readAnimationGraph":"plugin:preview|read_animation_graph","readAssetInfo":"plugin:preview|read_asset_info","readClipHeader":"plugin:preview|read_clip_header","readEngineProgram":"plugin:preview|read_engine_program","readMap":"plugin:preview|read_map","readMapCharacters":"plugin:preview|read_map_characters","readMapOutline":"plugin:preview|read_map_outline","readMapParticles":"plugin:preview|read_map_particles","readMapVariants":"plugin:preview|read_map_variants","readMaterialPrograms":"plugin:preview|read_material_programs","readSkin":"plugin:preview|read_skin","readSpell":"plugin:preview|read_spell","readVfxSystem":"plugin:preview|read_vfx_system","saveAssetCopy":"plugin:preview|save_asset_copy","vfxTemplates":"plugin:preview|vfx_templates"} as const;
