export const DEFAULT_LOCALE = "default";

export const LOCALES = [
  { value: "default", label: "Default (All Locales)" },
  { value: "en_us", label: "English (US)" },
  { value: "en_gb", label: "English (UK)" },
  { value: "en_au", label: "English (AU)" },
  { value: "en_ph", label: "English (PH)" },
  { value: "en_sg", label: "English (SG)" },
  { value: "ko_kr", label: "Korean" },
  { value: "ja_jp", label: "Japanese" },
  { value: "zh_cn", label: "Chinese (Simplified)" },
  { value: "zh_tw", label: "Chinese (Traditional)" },
  { value: "es_es", label: "Spanish (EU)" },
  { value: "es_mx", label: "Spanish (LATAM)" },
  { value: "es_ar", label: "Spanish (AR)" },
  { value: "pt_br", label: "Portuguese (BR)" },
  { value: "fr_fr", label: "French" },
  { value: "de_de", label: "German" },
  { value: "it_it", label: "Italian" },
  { value: "pl_pl", label: "Polish" },
  { value: "ro_ro", label: "Romanian" },
  { value: "el_gr", label: "Greek" },
  { value: "ru_ru", label: "Russian" },
  { value: "tr_tr", label: "Turkish" },
  { value: "cs_cz", label: "Czech" },
  { value: "hu_hu", label: "Hungarian" },
  { value: "th_th", label: "Thai" },
  { value: "vn_vn", label: "Vietnamese" },
  { value: "id_id", label: "Indonesian" },
  { value: "ms_my", label: "Malay" },
] as const;
